name: Build the project
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build and test code
        run: |
          sudo apt install -y build-essential python-is-python3
          make
          python3 unit_tests.py
